#Spring Boot Config

#端口
server:
  port: 8080

#文件上传路径
file-upload-path: E:/test

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://ip:端口/dds?useUnicode=true&characterEncoding=utf8
    username: 账号
    password: 密码
  mail:
    host: smtp.163.com
    username: fanshuye1304@163.com
    password: fanshuye1304

